trigger: none

pool:
  name: axion-project

stages:
- stage: DockerBuildAndPush
  displayName: Docker Build and Push for Ingestion Service

  jobs:
  - job: DockerBuildAndPush
    displayName: Docker Build and Push for Ingestion Service

    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'acr-sudsutar-svc-name'
        command: 'login'
    
    - task: Docker@2
      inputs:
        containerRegistry: 'acr-sudsutar-svc-name'
        repository: 'DockerBuildAndPush_IngestionService'
        command: 'buildAndPush'
        Dockerfile: '**/axion-ingestion-service/Dockerfile'



    